services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Atkins\Importmap\:
    resource: '../Classes/*'

  Atkins\Importmap\Middleware\ImportmapGenerator:
    public: true

  Atkins\Importmap\Service\ImportmapParserService:
    public: true